### ISSUE TITLE
pre-trained model described in README.md

### ISSUE THREAD

**Issue by ndruger** [YuhangMing/Semantic-Indoor-Place-Recognition#1]
In README.md
https://github.com/YuhangMing/Semantic-Indoor-Place-Recognition/blob/main/README.md#training-stage-1

> The training usually takes a day. We also provide our pretrained endocer-decoder [here](https://drive.google.com/drive/folders/1ClyEa7fygBkKZ5oEH-DQQYykj8RJJ51p?usp=sharing) if you want to skip the first training stage.
>
> Please download the folder and put it in the `results` directory. In the folder `Log_2021-06-16_02-31-04` we provide the model trained on the complete ScanNet dataset WITHOUT colour. And in the folder `Log_2021-06-16_02-42-30` we provide the model trained on the compltete ScanNet dataset WITH colour.

There are two files `Log_2021-06-11_02-47-11` and `Log_2021-06-11_04-20-14` in the shared filder( https://drive.google.com/drive/folders/1ClyEa7fygBkKZ5oEH-DQQYykj8RJJ51p?usp=sharing ).
But I can't found `Log_2021-06-16_02-31-04` and `Log_2021-06-16_02-42-30`.

Would you place `Log_2021-06-16_02-31-04` and `Log_2021-06-16_02-42-30` on the folder?

**Comment by YuhangMing** [comment]
Sorry, I uploaded the wrong folders. 
`Log_2021-06-16_02-31-04` and `Log_2021-06-16_02-42-30` should be available now.
